### ISSUE TITLE
Can't pass in parameters to online compiler

### ISSUE THREAD

**Issue by fritzone** [ethanhs/cce#12]
While trying the example from the main page with the options that are to be passed to the compiler I get the following error:

`thread 'main' panicked at 'could not find file -O3`

Some system info:

```
$ echo $SHELL
/usr/bin/zsh
```
running on Linux Mint:
```
$uname -a
Linux flap 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
and
```
$ rustc --version
rustc 1.39.0 (4560ea788 2019-11-04)
```
and the stacktrace:
```
$ RUST_BACKTRACE=full cce compile arm64g630 -- -O3
thread 'main' panicked at 'could not find file -O3', /home/fld/.cargo/registry/src/github.com-1ecc6299db9ec823/cce-0.1.0/src/tempedit.rs:50:53
stack backtrace:
   0:     0x5564901205df - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x5564901205df - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x5564901205df - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x5564901205df - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55648ff6e76c - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55649011fbd6 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55649011f840 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55649011f840 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55649011f840 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55649011ef8f - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55649011ef8f - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55649011eabf - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x55649011ea69 - std::panicking::begin_panic_fmt::hecb5f06c798651bd
                               at src/libstd/panicking.rs:335
  13:     0x55648fef82e4 - cce::main::h816b414482e3a5a6
  14:     0x55648fef9c63 - std::rt::lang_start::{{closure}}::h809a332ec974abb7
  15:     0x55648feede58 - main
  16:     0x7f8db666fb97 - __libc_start_main
  17:     0x55648fed839a - _start
  18:                0x0 - <unknown>
```

**Comment by JOE1994** [comment]
This also happens to me in Windows 10 OS. 
![image](https://user-images.githubusercontent.com/10286488/72846939-90681c80-3c6f-11ea-90df-c44368e30734.png)
